prod:

dev:
  .settings:
    # E_ALL | E_STRICT = 4095
    error_reporting:        4095
    web_debug:              on
    cache:                  off
    stats:                  off
    no_script_name:         off

test:
  .settings:
    # E_ALL | E_STRICT & ~E_NOTICE = 2047
    error_reporting:        2047
    cache:                  off
    stats:                  off
    web_debug:              off

all:
  .actions:
    login_module:           user
    login_action:           login

  .settings:
    unavailable_module:     content
    unavailable_action:     unavailable

    available:              on

    standard_helpers:       [Partial, Cache, Form, I18N]

    i18n:                   on

    use_database:           on

#    default_module:         default
#    default_action:         index
#    
#    error_404_module:       default
#    error_404_action:       error404
#    
#    login_module:           default
#    login_action:           login
#    
#    module_disabled_module: default
#    module_disabled_action: disabled
#    
#    secure_module:          default
#    secure_action:          secure
#
#  .settings:
#    available:              on
#
#    module_accessor:        module
#    action_accessor:        action
#
#    content_type:           html
#    
#    path_info_array:        SERVER
#    path_info_key:          PATH_INFO
#    
#    url_format:             PATH
#    
#
#    use_security:           on
#    
#    compressed:             on
#    
#    tidy:                   on
#    

#    
#    timeout:                1800
#    
#    suffix:                 .
#    
#    module_default:         on
#
#    standard_helpers:       [Partial, Cache, Form]
#
#    max_forwards:           20
#
#    web_debug:              off
#
#    cache:                  on
#    default_cache_lifetime: 86400
#
#    routing:                on
#    no_script_name:         on
#    relative_url_root:      
#
#    stats:                  off
#
#    # E_ERROR | E_USER_ERROR = 257
#    error_reporting:        257
